class_name Global
extends Node

const RED_TRANSITION_TIME = 2.0
const GREEN_TRANSITION_TIME = 2.0
const GREEN_INTERVAL = 5.0

const PLAYER_VIEW_DISTANCE = 60.0
const PLAYER_SWAP_CHARGE_TIME = 0.5
const PLAYER_SWAP_DISTANCE = 50.0
